config/routes.rb
Rails.application.routes.draw do
  resources :orders

  post '/update_order_status/:nonce', to: 'orders#update_order_status'

  constraints Clearance::Constraints::SignedIn.new do
    root to: "orders#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "clearance/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ActiveResource::Base
  self.site = "#{Rails.application.config.xpg_host}/api/v1"

  def self.create_invoice(order_id, nonce)
    invoice = Invoice.new(
      wallet_name:  'xpg-test',
      amount:       rand(1e10..10e12).to_i,
      external_id:  order_id,
      callback_url: "http://#{Rails.application.config.xpg_demo_host}:#{Rails.application.config.xpg_demo_port}/update_order_status/#{nonce}"
    )

    if invoice.save
      invoice
    else
      raise "couldnt save invoice: #{invoice.errors.inspect}"
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  before_destroy { qr_code.purge }

  has_one_attached :qr_code

  def invoice_details
    @details ||= Invoice.find(xpg_invoice_id)
  rescue ActiveResource::ResourceNotFound
    nil
  end

  def qr_code_html
    return '' unless qr_code.attached?
    ActiveStorage::Current.url_options = { protocol: 'http', host: Rails.application.config.xpg_demo_host, port: Rails.application.config.xpg_demo_port }
    HTTParty.get(qr_code.url)
  end

  def self.create_order(user)
    new_order_id = SecureRandom.uuid
    nonce = SecureRandom.uuid

    invoice = Invoice.create_invoice(new_order_id, nonce)

    new_order = Order.new(
      id:             new_order_id,
      user:           user,
      xpg_invoice_id: invoice.id,
      xpg_nonce:      nonce
    )
    new_order.save!

    new_order.qr_code.attach(io: StringIO.new(HTTParty.get(URI.parse(invoice.qr_code))), filename: "#{new_order_id}.svg")

    new_order
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login, except: :update_order_status
  before_action :set_order, only: %i[ show destroy ]
  before_action do
    ActiveStorage::Current.url_options = { protocol: request.protocol, host: request.host, port: request.port }
  end
  skip_before_action :verify_authenticity_token, only: :update_order_status

  # GET /orders
  def index
    @orders = current_user.orders
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.create_order(current_user)

    redirect_to @order
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: "Order was successfully destroyed."
  end

  def update_order_status
    @order = Order.find_by(xpg_nonce: params[:nonce])
    @order.update(status: params[:status])
    @order.qr_code.purge
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XpgDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <div class="alert alert-danger">
      This is a demo for <a href="https://github.com/snex/xpg", target="_new">XPG</a>. The code for it is <a href="https://github.com/snex/xpg-demo", target="_new">here</a>. This demo uses the monero STAGENET. DO NOT SEND REAL MONERO TO ANY ADDRESSES GIVEN HERE. IT WILL BE LOST FOREVER AND I AM NOT RESPONSIBLE FOR IT.
    </div>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id_id, style: "display: block" %>
    <%= form.text_field :user_id_id %>
  </div>

  <div>
    <%= form.label :xpg_invoice_id, style: "display: block" %>
    <%= form.text_field :xpg_invoice_id %>
  </div>

  <div>
    <%= form.label :xpg_nonce, style: "display: block" %>
    <%= form.text_field :xpg_nonce %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <div>
    <strong>Xpg invoice:</strong>
    <%= order.xpg_invoice_id %>
  </div>
  <div>
    <strong>Status:</strong>
    <%= order.status %>
  </div>
  <div>
    <strong>Payments Received:</strong>
    <% if order.invoice_details.blank? %>
      Invoice has been purged from XPG
    <% else %>
      <% order.invoice_details.payments.each_with_index do |payment, i| %>
        <div class="card">
          <div>
            <strong>Amount:</strong>
            <%= payment.amount %>
          </div>
          <div>
            <strong>Confirmations:</strong>
            <%= payment.confirmations %>
          </div>
          <div>
            <strong>Necessary Confirmations:</strong>
            <%= payment.necessary_confirmations %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div>
    <strong>Approx Time to Expire:</strong>
    <% if order.invoice_details.blank? %>
      Invoice has been purged from XPG
    <% else %>
      <%= distance_of_time_in_words(order.invoice_details.expires_at, Time.current.utc) %>
    <% end %>
  </div>
  <div>
    <strong>Total Amount Owed:</strong>
    <%= order.invoice_details&.amount || 'Invoice has been purged from XPG' %>
  </div>
  <div>
    <strong>Address To Send To:</strong>
    <%= order.invoice_details&.incoming_address || 'Invoice has been purged from XPG' %>
  </div>
  <div>
    <strong>Payment ID:</strong>
    <%= order.invoice_details&.payment_id || 'Invoice has been purged from XPG' %>
  </div>
  <div>
    <strong>Estimated Confirm Time After Payment Received:</strong>
    <% if order.invoice_details.blank? %>
      Invoice has been purged from XPG
    <% else %>
      <%= distance_of_time_in_words(order.invoice_details.estimated_confirm_time.seconds) %>
    <% end %>
  </div>
  <% if order.qr_code.attached? %>
    <div>
      <strong>Payment QR Code:</strong>
      <div class="alert alert-danger">DO NOT USE THIS ON A MAINNET MONERO WALLET YOU CAN LOSE YOUR COINS FOREVER. THIS IS JUST A DEMO.</div>
      <%= order.qr_code_html.html_safe %>
      <div class="alert alert-danger">DO NOT USE THIS ON A MAINNET MONERO WALLET YOU CAN LOSE YOUR COINS FOREVER. THIS IS JUST A DEMO.</div>
    </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <div>
      <%= link_to order.id, order %>
    </div>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>